name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup packages
      run: |
        sudo apt update -qq
        sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install \
          build-essential make libx11-dev libgl-dev libglu-dev libxxf86vm-dev libxrandr-dev libxi-dev
    - name: Build
      run: |
        cp Makefile.linux Makefile.common
        make
    - uses: actions/upload-artifact@v2
      with:
        name: glvnc
        path: src/bin/glvnc
